apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "service.fullname" .}}
  labels: {{- include "service.labels" . | nindent 4}}
data:
  {{- with .Values.configMap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
