{{- if not .Values.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}
type: Opaque
data:
  PRIVATE_KEY: {{ .Values.secrets.privateKey | b64enc }}
{{- end }}