[package]
name = "galxe-raffle"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { workspace = true }
sha2-v0-9-8 = { workspace = true }
raffle-lib = { path = "../lib" }
