// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: prover.proto

package prover

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProverService_Prove_FullMethodName = "/prover.ProverService/Prove"
)

// ProverServiceClient is the client API for ProverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProverServiceClient interface {
	// Generate SP1 zero-knowledge proof using the Prover Network
	Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error)
}

type proverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProverServiceClient(cc grpc.ClientConnInterface) ProverServiceClient {
	return &proverServiceClient{cc}
}

func (c *proverServiceClient) Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponse)
	err := c.cc.Invoke(ctx, ProverService_Prove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProverServiceServer is the server API for ProverService service.
// All implementations must embed UnimplementedProverServiceServer
// for forward compatibility.
type ProverServiceServer interface {
	// Generate SP1 zero-knowledge proof using the Prover Network
	Prove(context.Context, *ProveRequest) (*ProveResponse, error)
	mustEmbedUnimplementedProverServiceServer()
}

// UnimplementedProverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProverServiceServer struct{}

func (UnimplementedProverServiceServer) Prove(context.Context, *ProveRequest) (*ProveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prove not implemented")
}
func (UnimplementedProverServiceServer) mustEmbedUnimplementedProverServiceServer() {}
func (UnimplementedProverServiceServer) testEmbeddedByValue()                       {}

// UnsafeProverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProverServiceServer will
// result in compilation errors.
type UnsafeProverServiceServer interface {
	mustEmbedUnimplementedProverServiceServer()
}

func RegisterProverServiceServer(s grpc.ServiceRegistrar, srv ProverServiceServer) {
	// If the following call pancis, it indicates UnimplementedProverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProverService_ServiceDesc, srv)
}

func _ProverService_Prove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverServiceServer).Prove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverService_Prove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverServiceServer).Prove(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProverService_ServiceDesc is the grpc.ServiceDesc for ProverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prover.ProverService",
	HandlerType: (*ProverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prove",
			Handler:    _ProverService_Prove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prover.proto",
}
