replicaCount: 1

image:
  repository: ghcr.io/galxe/galxe-raffle/prover-service
  pullPolicy: IfNotPresent
  tag: "v0.3.3"

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi

useExistingSecrets: true
existingSecretName: "galxe-raffle-prover-service"
# Only used if useExistingSecrets is false
secrets:
  privateKey: ""

configMap:
  RUST_BACKTRACE: full
