name: golang

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Install dependencies
        working-directory: go
        run: go mod tidy

      - name: Build raffle package
        working-directory: go/pkg/raffle
        run: go build

      - name: Test raffle package
        working-directory: go/pkg/raffle
        run: go test
